### ISSUE TITLE
[feat] tune config yaml should be able to take a simple value too 

### ISSUE THREAD

**Issue by suzannejin** [mathysgrapotte/stimulus#119]
For example
```
model_params:
  sequence_length: 40
  kernel_size:
    space: [2,10]
    mode: randint
  kernel_number:
    space: [1,10]
    mode: randint
```
