### ISSUE TITLE
Automatic cross CI once docker container has been built

### ISSUE THREAD

**Issue by mathysgrapotte** [mathysgrapotte/stimulus#242]
### Description of feature

stimulus-py automatically builds a docker container at mathysgrapotte/stimulus-py:dev when a PR is successfully merged to dev. 

This container can then be used to test in the dev environment in the deepmodeloptim pipeline to see if the python package is inducing breaking changes. 

It would be nice if, upon completion in the stimulus-py repository, the CI in deepmodeloptim would be automatically triggered in the dev branch.

**Comment by mathysgrapotte** [comment]
below, a LLM answer to the question for information : 

Yes, it’s definitely possible. One common solution is to have your stimulus‑py GitHub Actions workflow trigger a CI run in the deepmodeloptim repository via a GitHub API call—typically using a repository dispatch event. 

### How It Works

1. **Trigger Event from stimulus‑py:**  
   In your stimulus‑py workflow (which builds and pushes your Docker image), add a step that sends a POST request to the GitHub API to trigger a repository dispatch event in the nf‑core/deepmodeloptim repository. You can pass along a custom event type (for example, `"docker_updated"`) and any payload data (like the new container tag).

2. **Listen in deepmodeloptim:**  
   In the deepmodeloptim repository, configure a GitHub Actions workflow to listen for `repository_dispatch` events with the corresponding event type. When this event is received, the workflow can run CI tests to verify that the new container does not break the pipeline.

### Example

**In stimulus‑py repository (after a successful Docker build and push):**

```yaml
- name: Trigger deepmodeloptim CI
  run: |
    curl -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${{ secrets.GITHUB_PAT }}" \
      https://api.github.com/repos/nf-core/deepmodeloptim/dispatches \
      -d '{"event_type": "docker_updated", "client_payload": {"container": "mathysgrapotte/stimulus:dev"}}'
```

> *Note:* Ensure you have created a Personal Access Token (PAT) with the required permissions (usually `repo` and `workflow` scopes) and added it as a secret (here, `GITHUB_PAT`) in the stimulus‑py repository.

**In deepmodeloptim repository (workflow file to run CI on dispatch):**

```yaml
name: CI on Container Update

on:
  repository_dispatch:
    types: [docker_updated]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          # Run your tests to ensure the new container works with the pipeline.
          nextflow run main.nf
```

### Why This Approach?

- **Cross-Repository Integration:**  
  This setup allows you to decouple your container build from the pipeline validation while still automating the process.

- **Flexibility:**  
  You can pass additional data (using `client_payload`) to further customize the CI run if needed.

- **GitHub-Native:**  
  Leveraging GitHub Actions and the repository_dispatch event means you don’t need to rely on third-party tools.

For more details on triggering workflows between repositories using repository dispatch, you can check out the GitHub documentation and community tutorials on this topic
